version: '3'
services:
  app:
    build: .
    ports:
      - 3000:3000
    
      
    depends_on:
      - db
  
  db:
    image: mongo:4
    environment:
      NEXT_PUBLIC_MONGO_URI: mongodb+srv://aman:12345@cluster0.tnh9cvk.mongodb.net/?retryWrites=true&w=majority



